name: ASP.NET Core CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Setup docker
      uses: docker/setup-buildx-action@v3
    - name: Build docker image (local only)
      uses: docker/build-push-action@v5
      with:
        push: false
        tags: passcore:local
        cache-from: type=gha
        cache-to: type=gha,mode=max
