name: Semantic Release

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    outputs:
      new-release-published: ${{ steps.semantic-release.outputs.new-release-published }}
      new-release-version: ${{ steps.semantic-release.outputs.new-release-version }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install semantic release
      run: |
        npm install -g semantic-release@21
        npm install -g @semantic-release/changelog
        npm install -g @semantic-release/git
        
    - name: Semantic Release
      id: semantic-release
      run: |
        npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    needs: semantic-release
    if: needs.semantic-release.outputs.new-release-published == 'true'
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'src/Unosquare.PassCore.Web/ClientApp/package-lock.json'
        
    - name: Restore .NET dependencies
      run: dotnet restore
      
    - name: Build .NET solution
      run: dotnet build --configuration Release --no-restore
      
    - name: Install npm dependencies
      run: npm ci
      working-directory: src/Unosquare.PassCore.Web/ClientApp
      
    - name: Build frontend
      run: npm run build
      working-directory: src/Unosquare.PassCore.Web/ClientApp
      
    - name: Publish .NET application
      run: dotnet publish --configuration Release --no-build --output ./publish --self-contained false
      
    - name: Set version info
      run: |
        $version = "${{ needs.semantic-release.outputs.new-release-version }}"
        $buildDate = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
        echo "Version: $version" > version.txt
        echo "Build Date: $buildDate" >> version.txt
        echo "Build Environment: GitHub Actions" >> version.txt
        
    - name: Create release archive
      run: |
        Compress-Archive -Path "./publish/*" -DestinationPath "passcore-${{ needs.semantic-release.outputs.new-release-version }}-windows.zip"
        
    - name: Upload release assets
      run: |
        gh release upload ${{ needs.semantic-release.outputs.new-release-version }} passcore-${{ needs.semantic-release.outputs.new-release-version }}-windows.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
